### ISSUE TITLE
Allow `frontendServerUrl` to be configured trough config-files

### ISSUE THREAD

**Issue by tajakobsen** [enonic/lib-nextjs-proxy#24]
We often copy the latest content from **production** to the **test-server** (or to use in **local** development).

By keeping `frontendServerUrl` in content (in the site config), we make it more difficult to move content between servers, since this value is specific for this exact server.

That is why we prefer to keep server-specific-config in config-files instead of content.

Can you add an alternative configuration of `frontendServerUrl` trough a file in `XP_HOME/config/...`

**Comment by espen42** [comment]
This is certainly important.

**Comment by sigdestad** [comment]
We will have to find a solution that supports multiple sites using the same app, but maybe save that for the next release?

**Comment by espen42** [comment]
https://github.com/enonic/doc-nextjs/issues/14
